<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.78.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Abstractions" Version="1.78.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Ollama" Version="1.78.0-alpha" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="ScottPlot.WPF" Version="5.0.36" />
    <PackageReference Include="Skender.Stock.Indicators" Version="2.7.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Main\Agents\Assistance\" />
    <Folder Include="Main\Entities\Stocks\NewFolder\" />
  </ItemGroup>

</Project>
