// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockPersistanceLib.Data;

#nullable disable

namespace StockPersistanceLib.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260727142238_AgentJsonMigration2")]
    partial class AgentJsonMigration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("StockValuationApp.Entities.Stocks.Metrics.YearlyFinancials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CapitalExpenditures")
                        .HasColumnType("REAL");

                    b.Property<double>("Dividends")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsEstimate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyFiguresDict")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("KeyFiguresJson");

                    b.Property<string>("KeyFiguresJson")
                        .HasColumnType("TEXT");

                    b.Property<double>("NmbrOfShares")
                        .HasColumnType("REAL");

                    b.Property<double>("OperatingCashFlow")
                        .HasColumnType("REAL");

                    b.Property<double>("Revenue")
                        .HasColumnType("REAL");

                    b.Property<int>("StockId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StockPrice")
                        .HasColumnType("REAL");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "Year")
                        .IsUnique();

                    b.ToTable("YearlyFinancials", t =>
                        {
                            t.Property("KeyFiguresJson")
                                .HasColumnName("KeyFiguresJson1");
                        });
                });

            modelBuilder.Entity("StockValuationApp.Entities.Stocks.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentAnalysisJson")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LastPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("StockValuationApp.Entities.Stocks.Metrics.YearlyFinancials", b =>
                {
                    b.HasOne("StockValuationApp.Entities.Stocks.Stock", null)
                        .WithMany("Financials")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("StockValuationApp.Entities.Stocks.Metrics.Earnings.Earning", "Earnings", b1 =>
                        {
                            b1.Property<int>("YearlyFinancialsId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("EbitMargin")
                                .HasColumnType("REAL");

                            b1.Property<double>("EbitValue")
                                .HasColumnType("REAL")
                                .HasColumnName("EbitValue");

                            b1.Property<decimal>("EbitdaMargin")
                                .HasColumnType("REAL");

                            b1.Property<double>("EbitdaValue")
                                .HasColumnType("REAL")
                                .HasColumnName("EbitdaValue");

                            b1.Property<decimal>("NetIncomeMargin")
                                .HasColumnType("REAL");

                            b1.Property<double>("NetIncomeValue")
                                .HasColumnType("REAL")
                                .HasColumnName("NetIncomeValue");

                            b1.HasKey("YearlyFinancialsId");

                            b1.ToTable("YearlyFinancials");

                            b1.WithOwner()
                                .HasForeignKey("YearlyFinancialsId");
                        });

                    b.OwnsOne("StockValuationApp.Entities.Stocks.Metrics.EnterpriseValue", "EnterpriseVal", b1 =>
                        {
                            b1.Property<int>("YearlyFinancialsId")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("CashAndEquivalents")
                                .HasColumnType("REAL")
                                .HasColumnName("CashAndEquivalents");

                            b1.Property<double>("LongTermDebt")
                                .HasColumnType("REAL")
                                .HasColumnName("LongTermDebt");

                            b1.Property<double>("MarketValue")
                                .HasColumnType("REAL")
                                .HasColumnName("MarketValue");

                            b1.Property<double>("ShortTermDebt")
                                .HasColumnType("REAL")
                                .HasColumnName("ShortTermDebt");

                            b1.HasKey("YearlyFinancialsId");

                            b1.ToTable("YearlyFinancials");

                            b1.WithOwner()
                                .HasForeignKey("YearlyFinancialsId");
                        });

                    b.Navigation("Earnings");

                    b.Navigation("EnterpriseVal");
                });

            modelBuilder.Entity("StockValuationApp.Entities.Stocks.Stock", b =>
                {
                    b.OwnsOne("StockLib.Main.Entities.Stocks.StockScore", "StockScore", b1 =>
                        {
                            b1.Property<int>("StockId")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("ConsensusScore")
                                .HasColumnType("REAL")
                                .HasColumnName("ConsensusScore");

                            b1.Property<double>("CostAdvScore")
                                .HasColumnType("REAL")
                                .HasColumnName("CostAdvScore");

                            b1.Property<double>("EpsGrowthScore")
                                .HasColumnType("REAL")
                                .HasColumnName("EpsGrowthScore");

                            b1.Property<double>("EvEbitScore")
                                .HasColumnType("REAL")
                                .HasColumnName("EvEbitScore");

                            b1.Property<double>("EvFcfScore")
                                .HasColumnType("REAL")
                                .HasColumnName("EvFcfScore");

                            b1.Property<double>("IntangAssetScore")
                                .HasColumnType("REAL")
                                .HasColumnName("IntangAssetScore");

                            b1.Property<double>("MarginExpScore")
                                .HasColumnType("REAL")
                                .HasColumnName("MarginExpScore");

                            b1.Property<double>("MarketVolatilityScore")
                                .HasColumnType("REAL")
                                .HasColumnName("MarketVolatilityScore");

                            b1.Property<double>("NetworkEffectScore")
                                .HasColumnType("REAL")
                                .HasColumnName("NetworkEffectScore");

                            b1.Property<double>("NonDisruptiveScore")
                                .HasColumnType("REAL")
                                .HasColumnName("NonDisruptiveScore");

                            b1.Property<double>("RevGrowthScore")
                                .HasColumnType("REAL")
                                .HasColumnName("RevGrowthScore");

                            b1.Property<double>("RoeRoicScore")
                                .HasColumnType("REAL")
                                .HasColumnName("RoeRoicScore");

                            b1.Property<double>("ScalabilityScore")
                                .HasColumnType("REAL")
                                .HasColumnName("ScalabilityScore");

                            b1.Property<double>("SectorGrowthScore")
                                .HasColumnType("REAL")
                                .HasColumnName("SectorGrowthScore");

                            b1.Property<double>("SwitchCostScore")
                                .HasColumnType("REAL")
                                .HasColumnName("SwitchCostScore");

                            b1.HasKey("StockId");

                            b1.ToTable("Stocks");

                            b1.WithOwner()
                                .HasForeignKey("StockId");
                        });

                    b.Navigation("StockScore");
                });

            modelBuilder.Entity("StockValuationApp.Entities.Stocks.Stock", b =>
                {
                    b.Navigation("Financials");
                });
#pragma warning restore 612, 618
        }
    }
}
